Add My Card
gabrysia694/MyPetSpotlight pull request #42
Opened 2023-04-28 11:27 UTC by Gallantfarhan

added my cat card and fill all the information.

2023-04-30 18:46 UTC, gabrysia694 requested changes

2023-04-30 18:46 UTC, gabrysia694 commented on index.html
> +      <img src="./assets/images/pusho.jpeg" alt="description of your picture">
Everything looks good apart from `alt="description of your picture"` which should be an actual description of your picture like "picture of the cat Pusho"

2023-05-06 15:28 UTC, Gallantfarhan commented
hey @gabrysia694 thanks for letting me know, I've added the alt description, check if everything is correct. thanks

2023-05-07 10:18 UTC, gabrysia694 approved these changes

2023-05-07 10:19 UTC, merged