Added my pet's name and characteristics
gabrysia694/MyPetSpotlight pull request #66
Opened 2023-05-24 21:13 UTC by RaghavGoel01

Please review the PR :)

2023-05-24 21:39 UTC, gabrysia694 requested changes

2023-05-24 21:39 UTC, gabrysia694 commented on index.html
> +/////////////////////
Looks good but please delete slashes on 1314 line

2023-05-25 08:12 UTC, RaghavGoel01 commented on index.html
> +/////////////////////
Deleted them @gabrysia694

2023-05-25 09:46 UTC, gabrysia694 approved these changes

2023-05-25 09:47 UTC, merged